version: 1

formatters:
  brief:
    format: '%(asctime)s %(message)s'
    datefmt: '%H:%M:%S'

  precise:
    format: '%(asctime)s : %(levelname)s : %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  verbose:
    format: '%(asctime)s : %(name)s : %(levelname)s : %(module)s : %(funcName)s : %(message)s'

handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: verbose
    stream: ext://sys.stdout

  error_handler:
    class: logging.handlers.WatchedFileHandler
    level: ERROR
    formatter: precise
    filename: error.log

  process_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: precise
    filename: process.log
    maxBytes: 1048576
    backupCount: 5

  move_handler:
    class: logging.handlers.WatchedFileHandler
    level: INFO
    formatter: brief
    filename: move.log


loggers:
  root:
    level: INFO
    handlers: [console_handler]

  process:
    level: DEBUG
    handlers: [console_handler, process_handler]
    propagate: false

  error:
    level: INFO
    handlers: [console_handler, process_handler, error_handler]
    propagate: false

  move:
    level: INFO
    handlers: [console_handler, process_handler, move_handler]
    propagate: false